spring:
  application:
    name: dizi-cloud

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:dizicloud
    username: sa
    password: ""
    generate-unique-name: false

  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    com.dizi.dz.controller: INFO
