delete from Ingredient_Ref;
delete from Dizi;
delete from Dizi_Order;

delete from Ingredient;
insert into Ingredient (id, name, type) values ('DIZS', 'Dizi Sangi', 'ZARF');
insert into Ingredient (id, name, type) values ('DIZM', 'Dizi Messi', 'ZARF');
insert into Ingredient (id, name, type) values ('DIZC', 'Dizi Chodani', 'ZARF');
insert into Ingredient (id, name, type) values ('DIZZ', 'Dizi Zoodpazi', 'ZARF');
insert into Ingredient (id, name, type) values ('GOJF', 'Goje Farangi', 'SABZIJAT');
insert into Ingredient (id, name, type) values ('SIBZ', 'Sibzamini', 'SABZIJAT');
insert into Ingredient (id, name, type) values ('PIAZ', 'Piaz', 'SABZIJAT');
insert into Ingredient (id, name, type) values ('SIR', 'Sir', 'SABZIJAT');
insert into Ingredient (id, name, type) values ('GGMA', 'Goosht Gosfandi - Mahiche', 'GOOSHT');
insert into Ingredient (id, name, type) values ('GGGH', 'Goosht Gosfandi - Ghalam', 'GOOSHT');
insert into Ingredient (id, name, type) values ('GGGD', 'Goosht Gosfandi - Gardan', 'GOOSHT');
insert into Ingredient (id, name, type) values ('GGGV', 'Goosht Gosfandi - Gholvegah', 'GOOSHT');
insert into Ingredient (id, name, type) values ('GMOR', 'Goosht Morgh', 'GOOSHT');
insert into Ingredient (id, name, type) values ('DGOS', 'Donbeh Gosfandi', 'CHARBI');
insert into Ingredient (id, name, type) values ('LBSF', 'Loobia Sefid', 'HOBOBAT');
insert into Ingredient (id, name, type) values ('LBGR', 'Loobia Ghermez', 'HOBOBAT');
insert into Ingredient (id, name, type) values ('NOKH', 'Nokhod', 'HOBOBAT');
insert into Ingredient (id, name, type) values ('NAMK', 'Namak', 'ADVIYEHJAT');
insert into Ingredient (id, name, type) values ('ZARD', 'Zardchoobeh', 'ADVIYEHJAT');
insert into Ingredient (id, name, type) values ('DARC', 'Darchin', 'ADVIYEHJAT');
insert into Ingredient (id, name, type) values ('FFGR', 'Felfel Ghermez', 'ADVIYEHJAT');
insert into Ingredient (id, name, type) values ('FFSI', 'Felfel Siah', 'ADVIYEHJAT');
insert into Ingredient (id, name, type) values ('ZIRE', 'Zire', 'ADVIYEHJAT');
insert into Ingredient (id, name, type) values ('LIMO', 'Limoo Amani', 'ADVIYEHJAT');
insert into Ingredient (id, name, type) values ('RBSN', 'Rob San''ati', 'SOS');
insert into Ingredient (id, name, type) values ('RBMH', 'Rob Mahali', 'SOS');
insert into Ingredient (id, name, type) values ('LAVH', 'Lavash', 'NOON');
insert into Ingredient (id, name, type) values ('BARB', 'Barbari', 'NOON');
insert into Ingredient (id, name, type) values ('SANG', 'Sangak', 'NOON');
insert into Ingredient (id, name, type) values ('BAGT', 'Baget', 'NOON');
insert into Ingredient (id, name, type) values ('TAFT', 'Taftoon', 'NOON');
insert into Ingredient (id, name, type) values ('KHKH', 'Khoshk Khorasooni', 'NOON');
insert into Ingredient (id, name, type) values ('KHGZ', 'Khoshk Ghazvini', 'NOON');
insert into Ingredient (id, name, type) values ('KHYZ', 'Khoshk Yazdi', 'NOON');
insert into Ingredient (id, name, type) values ('KHST', 'Khoshk Sonati', 'NOON');
insert into Ingredient (id, name, type) values ('MSTS', 'Mast Sade', 'DORCHIN');
insert into Ingredient (id, name, type) values ('MTSM', 'Mast Moosir', 'DORCHIN');
insert into Ingredient (id, name, type) values ('ZEIT', 'Zeitoon', 'DORCHIN');
insert into Ingredient (id, name, type) values ('ZPVD', 'Zeitoon Parvarde', 'DORCHIN');
insert into Ingredient (id, name, type) values ('TSLT', 'Torshi Lite', 'DORCHIN');
insert into Ingredient (id, name, type) values ('STSR', 'Sir Torshi', 'DORCHIN');
insert into Ingredient (id, name, type) values ('TSFL', 'Torshi Felfel', 'DORCHIN');
insert into Ingredient (id, name, type) values ('TSBD', 'Torshi Bandari', 'DORCHIN');
insert into Ingredient (id, name, type) values ('TSKG', 'Torshi Kalam Ghermez', 'DORCHIN');
insert into Ingredient (id, name, type) values ('TSHB', 'Torshi Haft Bijar', 'DORCHIN');
insert into Ingredient (id, name, type) values ('TSBDM', 'Torshi Bademjoon', 'DORCHIN');
insert into Ingredient (id, name, type) values ('TSAN', 'Torshi Anbe', 'DORCHIN');
insert into Ingredient (id, name, type) values ('TSPZ', 'Torshi Piaz', 'DORCHIN');
insert into Ingredient (id, name, type) values ('TSNZ', 'Torshi Nazkhaton', 'DORCHIN');
insert into Ingredient (id, name, type) values ('TSKH', 'Torshi Khorfe', 'DORCHIN');
insert into Ingredient (id, name, type) values ('SBKH', 'Sabzi Khordan', 'DORCHIN');
insert into Ingredient (id, name, type) values ('PHLG', 'Piaz Halghe''ei', 'DORCHIN');
insert into Ingredient (id, name, type) values ('SLSH', 'Salad Shirazi', 'DORCHIN');
insert into Ingredient (id, name, type) values ('SLKH', 'Salad Kahoo', 'DORCHIN');
insert into Ingredient (id, name, type) values ('SLKM', 'Salad Kalam', 'DORCHIN');
insert into Ingredient (id, name, type) values ('KHSH', 'Khiarshoor', 'DORCHIN');
insert into Ingredient (id, name, type) values ('DOUG', 'Dough', 'NOSHIDANI');
insert into Ingredient (id, name, type) values ('DELS', 'Delster', 'NOSHIDANI');
insert into Ingredient (id, name, type) values ('NOSH', 'Noshabeh', 'NOSHIDANI');
insert into Ingredient (id, name, type) values ('AB', 'Ab', 'NOSHIDANI');
insert into Ingredient (id, name, type) values ('ABGZ', 'Ab Gazdar', 'NOSHIDANI');

